***LABORATORIO N°1***

**Integrantes:**

*Laura Sofia Mosquera Gruezo*

*María Celeste Isaza Vergara*

1. Desarrolle los siguientes programas usando VS code:


A. Investigue como definir funciones en Python usando “def”, describa un breve ejemplo.


*Solución:*

Para crear o definir una función en Phyton se utiliza la palabra clave "def" y se sigue la siguiente sintaxis:
*def nombre_funcion(parámetros):*

In [ ]:
#EJEMPLO:
def multiplicacion (a,b):
    resultado =a*b
    return resultado
print(multiplicacion(6,9))


54


B. Desarrolle una calculadora básica usando funciones, en la cual ingresen 2 números enteros y el
tipo de operación a realizar en string. Como resultado la calculadora debe arrojar la operación
deseada entre los 2 números.


*Solucion:*

In [ ]:
#Ingreso de variables:
a=int(input("Ingrese un numero para a:"))
b=int(input("Ingrese un numero para b:"))
print(a,b)
#Definicion de variables: 
def suma (a,b):
       resultado= a+b
       return resultado

def resta (a,b):
       resultado= a-b
       return resultado

def multiplicacion (a,b):
       resultado= a*b
       return resultado
      
def division (a,b):
       if b==0:
             return "Error: no existe division por cero"
       resultado= a/b
       return resultado

def modulo (a,b):
       resultado= a%b
       return resultado

def cal(a,b,operacion):
    #Creacion del diccionario de operaciones:
    operaciones ={
          "suma":suma,
          "resta":resta,
          "multiplicacion":multiplicacion,
          "division":division,
          "modulo":modulo

    }
    if operacion in operaciones:
      return operaciones[operacion](a,b)
    else:
          return "operacion no valida"
operacion=input("Ingresar operación de desea ejecutar:")
resultado=cal(a,b,operacion)
print(f"El resultado de la {operacion} es:{resultado}")


144 12
El resultado de la modulo es:0


C. Desarrolle un algoritmo en el cual usted pueda definir el tamaño de una matriz cuadrada con
un numero N, posteriormente le pida cada uno de los valores de la matriz con la indicación
exacta de donde ira ubicado. Finalmente, el algoritmo debe retornar al usuario la matriz
deseada y su transpuesta.

*Solución:*

In [ ]:
import numpy as np
#Ingreso del tamaño de la matriz:
m = int(input("Ingrese el número de filas (m): "))
n = int(input("Ingrese el número de columnas (n): "))
#Creación de la matriz:
matriz =np.zeros((m,n))
#Ingreso de los valores para la matriz:
for i in range(m):
    for j in range(n):
        numero = float(input(f"Ingrese el valor para la posición ({i},{j}): "))
        matriz[i][j] = round(numero)
        print(f" \n Los valores ingresados en [{i},{j}]=", numero )
print("\n La matriz creada es: ")
print(matriz)
#Calculo de la matriz transpuesta:
matriz_transpuesta=matriz.T
print("\n La matriz transpuesta es: ")
print(matriz_transpuesta)

 
 Los valores ingresados en [0,0]= 1.0
 
 Los valores ingresados en [0,1]= 2.0
 
 Los valores ingresados en [1,0]= 3.0
 
 Los valores ingresados en [1,1]= 4.0

 La matriz creada es: 
[[1. 2.]
 [3. 4.]]

 La matriz transpuesta es: 
[[1. 3.]
 [2. 4.]]


 D. Desarrolle un algoritmo que reciba un mes y día especifico, y nos dé una aproximación para esa
fecha sobre la estación climática en la cual estamos.


*Solución:*

In [ ]:
#Definición de la función estación:
def estacion (mes,dia):
    #Creación del diccionario de meses válidos:
    meses_validos= {
        "enero":31,
        "febrero":29,
        "marzo":31,
        "abril":30,
        "mayo":31,
        "junio":30,
        "julio":31,
        "agosto":31,
        "septiembre":30,
        "octubre":31,
        "noviembre":30,
        "diciembre":31
    }
    mes=mes.lower() #Flexibilidad 
    #Para saber sí el mes es válido:
    if mes not in meses_validos:
        return " El mes ingresado no es válido"
    #Para saber sí el día es válido:
    if dia<1 or dia>meses_validos[mes]:
        return f"El día {dia} no es valido para el mes de {mes}"
    #Determinación de las estaciones:
    if (mes=="diciembre" and dia>=21) or (mes in ["enero","febrero"]) or (mes=="marzo" and dia<=20):
        return "Estamos en verano"
    elif (mes=="marzo" and dia>=21) or (mes in ["abril","mayo"]) or (mes=="junio" and dia<=20):
        return "Estamos en otoño"
    elif (mes=="junio" and dia>=21) or (mes in ["julio","agosto"]) or (mes=="septiembre" and dia<=20):
        return "Estamos en invierno"
    elif (mes=="septiembre" and dia>=21) or (mes in ["octubre","noviembre"]) or (mes=="diciembre" and dia<=20):
        return "Estamos en primavera"
    else:
        return "Error"
#Ingreso de los datos:
mes=str(input("Ingrese el mes que desea consultar : "))
dia=int(input("Ingrese el día que desea consultar: "))
print(mes,dia)
resultado=estacion(mes,dia)
print(resultado)

noviembre 31
El día 31 no es valido para el mes de noviembre


E. Desarrolle un algoritmo que sea capaz de sumar una matriz aleatoria con una matriz ingresada
por el usuario.


*Solución:*

In [50]:
import numpy as np 
#Creación de la matriz aleatoria:_
m = int(input("Ingrese el número de filas (m): "))
n = int(input("Ingrese el número de columnas (n): "))
matriz_aleatoria=np.round(np.random.rand(m,n),2)
print(" \n La matriz aleatoria es:")
print("\n", matriz_aleatoria)
#Creacion de la matriz por el usuario:
matriz_usuario = np.zeros((m,n))
for i in range(m):
    for j in range(n):
        matriz_usuario[i][j] = float(input(f"Ingrese el valor para la posición ({i},{j}): "))
print(" \n La matriz creada por el usuario es:")
print("\n", matriz_usuario)
#Suma de las dos matrices:
MATRIZ_R=matriz_aleatoria+matriz_usuario 
print("\n El resultado de la suma de las dos matrices es: ")
print("\n", MATRIZ_R)

 
 La matriz aleatoria es:

 [[0.3  0.28]
 [0.55 0.58]]
 
 La matriz creada por el usuario es:

 [[12. 13.]
 [45. 78.]]

 El resultado de la suma de las dos matrices es: 

 [[12.3  13.28]
 [45.55 78.58]]


F. Una empresa de comercio electrónico necesita un programa en Python que procese reseñas de
clientes.

El programa debe:

1. Pedir al usuario que ingrese varias reseñas de productos (mínimo 3).

2. Convertir todas las reseñas a minúsculas y eliminar signos de puntuación básicos (. , ! ?).

3. Guardar cada reseña en una lista.

4. Crear un diccionario de frecuencias que indique cuántas veces aparece cada palabra en
todas las reseñas combinadas.

5. Identificar y mostrar: Las 3 palabras más frecuentes en las reseñas.

*Solución:*

In [ ]:
import string
from collections import Counter
def procesar_reseñas():
    # Reseñas:
    reseñas = []
    cantidad_reseñas=int(input("Ingrese la cantidad de reseñas que desea dar: "))
    # Recolectar las 3 reseñas del usuario:
    for i in range (cantidad_reseñas):
        reseña = input(f"Ingrese la reseña {i+1}: ")
        reseñas.append(reseña)
    for r in reseñas:
        print("\n", r)
    # Conversión a minúsculas y eliminación de signos de puntuación:
    palabras = []
    for reseña in reseñas:
        reseña_limpia = reseña.lower().translate(str.maketrans('', '', string.punctuation))
        palabras.extend(reseña_limpia.split())
        print( "\n" ,reseña_limpia)
    # Contar las palabras:
    frecuencias = Counter(palabras)
    # Identificación de las 3 palabras más comunes:
    print("\nLas 3 palabras más frecuentes son:")
    for palabra, frecuencia in frecuencias.most_common(3):
        print(f"'{palabra}': {frecuencia} veces")
# Ejecutar el programa:
if __name__ == "__main__":
    procesar_reseñas()


 EL SHAMPOO NO ES HIDRATANTE, PESIMO.

 LOS ENVIOS SON MUY DEMORADOS, DICEN QUE LLEGA EN UNA FECHA Y LLEGA UN SIGLO DESPUES.

 HAN LLEGADO ROTO LOS EMPAQUE.

 HICE MI PEDIDO Y SE HUNDIÓ EL CONTENEDOR.

 el shampoo no es hidratante pesimo

 los envios son muy demorados dicen que llega en una fecha y llega un siglo despues

 han llegado roto los empaque

 hice mi pedido y se hundió el contenedor

Las 3 palabras más frecuentes son:
'el': 2 veces
'los': 2 veces
'llega': 2 veces
